#!/usr/bin/env node
/**
 * Import of the 6 legalPage documents from converted HTML fixtures
 * (src/content/legal-bodies, generated by scripts/convert-legal-html.py).
 *
 * Usage:
 *   node scripts/import-legal.mjs                 # dry run (default)
 *   node scripts/import-legal.mjs --dataset production
 *   SANITY_API_WRITE_TOKEN=… node scripts/import-legal.mjs --write --dataset production
 *
 * The dry run compares against the dataset (public read, or raw with a token)
 * and writes reports/legal-import.ndjson + reports/legal-import-dry-run.json.
 * --write commits one transaction of createOrReplace for exactly these 6
 * legalPage ids. Nothing else is created, patched or deleted. The token is
 * never printed.
 */
import { mkdir, readFile, writeFile } from "node:fs/promises";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

import { createClient } from "@sanity/client";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const projectId = "dyuqkn8c";
const apiVersion = "2026-09-01";
const write = process.argv.includes("--write");

function flagValue(name) {
  const index = process.argv.indexOf(name);
  return index === -1 ? undefined : process.argv[index + 1];
}

const LEGAL_IDS = [
  "legal-privacy-pl",
  "legal-privacy-en",
  "legal-terms-pl",
  "legal-terms-en",
  "legal-cookies-pl",
  "legal-newsletter-pl",
];

async function loadBody(slug) {
  return JSON.parse(
    await readFile(
      join(root, "src/content/legal-bodies", `${slug}.json`),
      "utf8",
    ),
  );
}

function noticeBody(href, linkLabel) {
  return [
    {
      _type: "block",
      _key: "en-notice",
      style: "normal",
      children: [
        {
          _type: "span",
          _key: "k0",
          text: "This page does not include an English translation of the legal document. The binding version is the Polish text.",
          marks: [],
        },
      ],
      markDefs: [],
    },
    {
      _type: "block",
      _key: "en-notice-link",
      style: "normal",
      children: [
        { _type: "span", _key: "k0", text: linkLabel, marks: ["to-pl"] },
      ],
      markDefs: [{ _type: "link", _key: "to-pl", href }],
    },
  ];
}

const [privacy, cookies, terms, newsletter] = await Promise.all([
  loadBody("polityka-prywatnosci"),
  loadBody("lista-cookies-i-identyfikatorow"),
  loadBody("regulamin"),
  loadBody("regulamin-newslettera"),
]);

const docs = [
  {
    _id: "legal-privacy-pl",
    _type: "legalPage",
    language: "pl",
    title: privacy.title,
    slug: { _type: "slug", current: "polityka-prywatnosci" },
    effectiveFrom: privacy.effectiveFrom,
    seo: {
      _type: "seo",
      title: "Polityka prywatności",
      description: privacy.seoDescription,
    },
    translation: { _type: "reference", _ref: "legal-privacy-en" },
    body: privacy.body,
  },
  {
    _id: "legal-privacy-en",
    _type: "legalPage",
    language: "en",
    title: "Privacy policy",
    slug: { _type: "slug", current: "privacy" },
    effectiveFrom: privacy.effectiveFrom,
    seo: {
      _type: "seo",
      title: "Privacy policy",
      description:
        "The binding version of this document is the Polish privacy policy.",
    },
    translation: { _type: "reference", _ref: "legal-privacy-pl" },
    body: noticeBody(
      "/polityka-prywatnosci/",
      "Read the Polish privacy policy",
    ),
  },
  {
    _id: "legal-terms-pl",
    _type: "legalPage",
    language: "pl",
    title: terms.title,
    slug: { _type: "slug", current: "regulamin" },
    effectiveFrom: terms.effectiveFrom,
    seo: {
      _type: "seo",
      title: "Regulamin",
      description: terms.seoDescription,
    },
    translation: { _type: "reference", _ref: "legal-terms-en" },
    body: terms.body,
  },
  {
    _id: "legal-terms-en",
    _type: "legalPage",
    language: "en",
    title: "Terms",
    slug: { _type: "slug", current: "terms" },
    effectiveFrom: terms.effectiveFrom,
    seo: {
      _type: "seo",
      title: "Terms",
      description: "The binding version of this document is the Polish terms.",
    },
    translation: { _type: "reference", _ref: "legal-terms-pl" },
    body: noticeBody("/regulamin/", "Read the Polish terms"),
  },
  {
    _id: "legal-cookies-pl",
    _type: "legalPage",
    language: "pl",
    title: cookies.title,
    slug: { _type: "slug", current: "lista-cookies-i-identyfikatorow" },
    effectiveFrom: cookies.effectiveFrom,
    seo: {
      _type: "seo",
      title: "Lista cookies i identyfikatorów",
      description: cookies.seoDescription,
    },
    body: cookies.body,
  },
  {
    _id: "legal-newsletter-pl",
    _type: "legalPage",
    language: "pl",
    title: newsletter.title,
    slug: { _type: "slug", current: "regulamin-newslettera" },
    effectiveFrom: newsletter.effectiveFrom,
    seo: {
      _type: "seo",
      title: "Regulamin newslettera",
      description: newsletter.seoDescription,
    },
    body: newsletter.body,
  },
];

function assertImportable(documents) {
  const ids = documents.map((doc) => doc._id).sort();
  if (JSON.stringify(ids) !== JSON.stringify([...LEGAL_IDS].sort())) {
    throw new Error(`Nieoczekiwane id dokumentów: ${ids.join(", ")}`);
  }
  for (const doc of documents) {
    if (doc._type !== "legalPage") {
      throw new Error(`${doc._id}: typ ${doc._type} zamiast legalPage`);
    }
    const missingKey = (value, where) => {
      if (Array.isArray(value)) {
        value.forEach((item, index) => {
          if (item && typeof item === "object" && !item._key) {
            throw new Error(`${doc._id}: brak _key w ${where}[${index}]`);
          }
          missingKey(item, `${where}[${index}]`);
        });
      } else if (value && typeof value === "object") {
        for (const [key, child] of Object.entries(value)) {
          if (key === "headers" || key === "cells") continue;
          missingKey(child, `${where}.${key}`);
        }
      }
    };
    missingKey(doc.body, "body");
  }
}

function stableJson(value) {
  if (Array.isArray(value)) return `[${value.map(stableJson).join(",")}]`;
  if (value && typeof value === "object") {
    return `{${Object.keys(value)
      .filter(
        (key) => !["_rev", "_createdAt", "_updatedAt", "_system"].includes(key),
      )
      .sort()
      .map((key) => `${JSON.stringify(key)}:${stableJson(value[key])}`)
      .join(",")}}`;
  }
  return JSON.stringify(value);
}

function blockText(block) {
  return (block.children ?? []).map((child) => child.text ?? "").join("");
}

function compare(doc, existing) {
  if (!existing) return { id: doc._id, action: "create" };
  const fields = [...new Set([...Object.keys(doc), ...Object.keys(existing)])]
    .filter(
      (key) => !["_rev", "_createdAt", "_updatedAt", "_system"].includes(key),
    )
    .filter((key) => stableJson(doc[key]) !== stableJson(existing[key]))
    .sort();
  if (fields.length === 0) return { id: doc._id, action: "unchanged" };
  const result = { id: doc._id, action: "replace", fields };
  if (fields.includes("body") && Array.isArray(existing.body)) {
    const before = existing.body;
    const after = doc.body;
    const changedBlocks = after
      .map((block, index) => ({ index, block, old: before[index] }))
      .filter(({ block, old }) => !old || blockText(block) !== blockText(old))
      .map(({ index, block, old }) => ({
        index,
        before: old ? blockText(old).length : null,
        after: blockText(block).length,
      }));
    result.body = {
      blocksBefore: before.length,
      blocksAfter: after.length,
      textChangedBlocks: changedBlocks,
    };
  }
  return result;
}

assertImportable(docs);

const dataset = flagValue("--dataset");
const token = process.env.SANITY_API_WRITE_TOKEN?.trim() || undefined;
// A read token is enough for the dry-run comparison (raw perspective shows drafts).
const readToken =
  token || process.env.SANITY_API_READ_TOKEN?.trim() || undefined;

if (write && !dataset) {
  console.error("--write wymaga jawnego --dataset <nazwa>.");
  process.exit(2);
}
if (write && !token) {
  console.error("--write wymaga SANITY_API_WRITE_TOKEN w środowisku.");
  process.exit(2);
}

let existing = null;
let drafts = [];
let readMode = "none";
if (dataset) {
  const client = createClient({
    projectId,
    dataset,
    apiVersion,
    useCdn: false,
    ...(readToken
      ? { token: readToken, perspective: "raw" }
      : { perspective: "published" }),
  });
  const draftIds = LEGAL_IDS.map((id) => `drafts.${id}`);
  const found = await client.fetch("*[_id in $ids]", {
    ids: [...LEGAL_IDS, ...draftIds],
  });
  existing = new Map(found.map((doc) => [doc._id, doc]));
  drafts = found.map((doc) => doc._id).filter((id) => id.startsWith("drafts."));
  readMode = readToken ? "raw (token)" : "published (public)";
}

const plan = docs.map((doc) =>
  existing
    ? compare(doc, existing.get(doc._id))
    : { id: doc._id, action: "createOrReplace" },
);

const report = {
  mode: write ? "write" : "dry-run",
  dataset: dataset ?? null,
  readMode,
  mutation: "createOrReplace",
  documentCount: docs.length,
  plan,
  drafts,
  stableIds: docs.map((doc) => ({
    id: doc._id,
    type: doc._type,
    slug: doc.slug.current,
  })),
  sources: {
    polityka: "https://www.zawlodzki.pl/polityka-prywatnosci",
    cookies: "https://www.zawlodzki.pl/lista-cookies-i-identyfikatorow",
    regulamin: "https://www.zawlodzki.pl/regulamin",
    newsletter: "https://www.zawlodzki.pl/regulamin-newslettera",
  },
  gaps: [
    "EN nie ma źródła prawnego — dokumenty privacy/terms mają tylko informację, że wiążąca jest wersja PL.",
    "Treść PL pochodzi ze spółki Wellbiz / zawlodzki.pl (B2B) i wymaga redakcji B2C przed produkcją.",
  ],
};

const outDir = join(root, "reports");
await mkdir(outDir, { recursive: true });
const ndjsonPath = join(outDir, "legal-import.ndjson");
const reportPath = join(outDir, "legal-import-dry-run.json");
await writeFile(
  ndjsonPath,
  docs.map((doc) => JSON.stringify(doc)).join("\n") + "\n",
);
await writeFile(reportPath, JSON.stringify(report, null, 2));

for (const item of plan) {
  const detail = item.fields ? ` (${item.fields.join(", ")})` : "";
  console.log(`${item.action} legalPage ${item.id}${detail}`);
}
if (drafts.length > 0) {
  console.log(`drafts (nie są nadpisywane): ${drafts.join(", ")}`);
}

if (!write) {
  console.log(
    JSON.stringify(
      { ok: true, mode: "dry-run", ndjson: ndjsonPath, report: reportPath },
      null,
      2,
    ),
  );
  process.exit(0);
}

const writer = createClient({
  projectId,
  dataset,
  apiVersion,
  token,
  useCdn: false,
});
const transaction = writer.transaction();
for (const doc of docs) transaction.createOrReplace(doc);
const result = await transaction.commit({ visibility: "sync" });
console.log(
  JSON.stringify(
    {
      ok: true,
      mode: "write",
      dataset,
      transactionId: result.transactionId,
      documentIds: docs.map((doc) => doc._id),
    },
    null,
    2,
  ),
);
