// Jedynym aktywnym źródłem wartości jest design-system/tokens.json.

function srgbChannel(value) {
  const s = value / 255;
  return s <= 0.04045 ? s / 12.92 : ((s + 0.055) / 1.055) ** 2.4;
}

export function relativeLuminance(hex) {
  const n = Number.parseInt(hex.replace("#", ""), 16);
  const r = (n >> 16) & 255;
  const g = (n >> 8) & 255;
  const b = n & 255;
  return (
    0.2126 * srgbChannel(r) + 0.7152 * srgbChannel(g) + 0.0722 * srgbChannel(b)
  );
}

export function contrastRatio(hexA, hexB) {
  const a = relativeLuminance(hexA);
  const b = relativeLuminance(hexB);
  const lighter = Math.max(a, b);
  const darker = Math.min(a, b);
  return (lighter + 0.05) / (darker + 0.05);
}

export function hexToOklch(hex) {
  const n = Number.parseInt(hex.slice(1), 16);
  const [r, g, b] = [
    srgbChannel((n >> 16) & 255),
    srgbChannel((n >> 8) & 255),
    srgbChannel(n & 255),
  ];
  const l = Math.cbrt(0.4122214708 * r + 0.5363325363 * g + 0.0514459929 * b);
  const m = Math.cbrt(0.2119034982 * r + 0.6806995451 * g + 0.1073969566 * b);
  const s = Math.cbrt(0.0883024619 * r + 0.2817188376 * g + 0.6299787005 * b);
  const lightness = 0.2104542553 * l + 0.793617785 * m - 0.0040720468 * s;
  const a = 1.9779984951 * l - 2.428592205 * m + 0.4505937099 * s;
  const bb = 0.0259040371 * l + 0.7827717662 * m - 0.808675766 * s;
  const chroma = Math.hypot(a, bb);
  const hue = ((Math.atan2(bb, a) * 180) / Math.PI + 360) % 360;
  return `oklch(${lightness.toFixed(9)} ${chroma < 0.000001 ? "0 none" : `${chroma.toFixed(9)} ${hue.toFixed(6)}`})`;
}

const tokenValue = (value) => (typeof value === "string" ? value : value.value);
const declarations = (values) =>
  Object.entries(values).map(
    ([name, value]) => `  --ao-${name}: ${tokenValue(value)};`,
  );

export function generateLegacyAliasesCss(system) {
  return [
    "/* Generated by scripts/generate-tokens.mjs. Legacy layouts only. */",
    ":root {",
    ...Object.entries(system.legacyAliases).map(
      ([name, value]) => `  --${name}: ${value};`,
    ),
    "}",
    "",
  ].join("\n");
}

export function generateTokensCss(system) {
  const lines = [
    "/* Generated by scripts/generate-tokens.mjs. Edit tokens.json, not this file. */",
    ":root {",
    ...declarations(system.tokens),
    "  color-scheme: light;",
    "}",
    '[data-theme="dark"] { color-scheme: dark; }',
    "@media (prefers-color-scheme: dark) {",
    ':root:not([data-theme="light"]) { color-scheme: dark; }',
    "}",
  ];
  lines.push(
    "@supports not (color: light-dark(white, black)) {",
    '[data-theme="dark"] {',
    ...declarations(system.dark),
    "}",
    "@media (prefers-color-scheme: dark) {",
    ':root:not([data-theme="light"]) {',
    ...declarations(system.dark),
    "}",
    "}",
    "}",
    "@supports (color: light-dark(white, black)) {",
    ":root {",
    ...Object.entries(system.tokens)
      .filter(([, value]) => /^#[\da-f]{6}$/i.test(tokenValue(value)))
      .map(([name, value]) => {
        const light = hexToOklch(tokenValue(value));
        return `  --ao-${name}: ${system.dark[name] ? `light-dark(${light}, ${hexToOklch(system.dark[name])})` : light};`;
      }),
    "}",
    "}",
  );
  for (const breakpoint of system.responsive) {
    lines.push(
      `@media (min-width: ${breakpoint.minWidth}px) {`,
      ":root {",
      ...declarations(breakpoint.values),
      "}",
      "}",
    );
  }
  return lines.join("\n") + "\n";
}
