// Jedynym aktywnym źródłem wartości jest design-system/tokens.json.

function srgbChannel(value) {
  const s = value / 255;
  return s <= 0.04045 ? s / 12.92 : ((s + 0.055) / 1.055) ** 2.4;
}

export function relativeLuminance(hex) {
  const n = Number.parseInt(hex.replace("#", ""), 16);
  const r = (n >> 16) & 255;
  const g = (n >> 8) & 255;
  const b = n & 255;
  return (
    0.2126 * srgbChannel(r) + 0.7152 * srgbChannel(g) + 0.0722 * srgbChannel(b)
  );
}

export function contrastRatio(hexA, hexB) {
  const a = relativeLuminance(hexA);
  const b = relativeLuminance(hexB);
  const lighter = Math.max(a, b);
  const darker = Math.min(a, b);
  return (lighter + 0.05) / (darker + 0.05);
}

export function generateTokensCss(system) {
  const declarations = (values, prefix = "ao") =>
    Object.entries(values).map(
      ([name, value]) =>
        `  --${prefix}-${name}: ${typeof value === "string" ? value : value.value};`,
    );
  const aliases = Object.entries(system.legacyAliases).map(
    ([name, value]) => `  --${name}: ${value};`,
  );
  const lines = [
    "/* Generated by scripts/generate-tokens.mjs. Edit tokens.json, not this file. */",
    ":root {",
    ...declarations(system.tokens),
    ...Object.entries(system.legacyAliases).map(
      ([name, value]) => `  --${name}: ${value};`,
    ),
    "}",
  ];
  lines.push(
    '[data-theme="dark"] {',
    ...declarations(system.dark),
    ...aliases,
    "}",
    "@media (prefers-color-scheme: dark) {",
    ':root:not([data-theme="light"]) {',
    ...declarations(system.dark),
    ...aliases,
    "}",
    "}",
  );
  for (const breakpoint of system.responsive) {
    lines.push(
      `@media (min-width: ${breakpoint.minWidth}px) {`,
      ":root {",
      ...declarations(breakpoint.values),
      "}",
      "}",
    );
  }
  return lines.join("\n") + "\n";
}
