// Jedynym aktywnym źródłem wartości jest design-system/tokens.json.
export function generateTokensCss(system) {
  const declarations = (values, prefix = "ao") =>
    Object.entries(values).map(
      ([name, value]) =>
        `  --${prefix}-${name}: ${typeof value === "string" ? value : value.value};`,
    );
  const aliases = Object.entries(system.legacyAliases).map(
    ([name, value]) => `  --${name}: ${value};`,
  );
  const lines = [
    "/* Generated by scripts/generate-tokens.mjs. Edit tokens.json, not this file. */",
    ":root {",
    ...declarations(system.tokens),
    ...Object.entries(system.legacyAliases).map(
      ([name, value]) => `  --${name}: ${value};`,
    ),
    "}",
  ];
  lines.push(
    '[data-theme="dark"] {',
    ...declarations(system.dark),
    ...aliases,
    "}",
    "@media (prefers-color-scheme: dark) {",
    ':root:not([data-theme="light"]) {',
    ...declarations(system.dark),
    ...aliases,
    "}",
    "}",
  );
  for (const breakpoint of system.responsive) {
    lines.push(
      `@media (min-width: ${breakpoint.minWidth}px) {`,
      ":root {",
      ...declarations(breakpoint.values),
      "}",
      "}",
    );
  }
  return lines.join("\n") + "\n";
}
